spring:
  application:
    name: mini-ecomm
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: kj
    password: kj
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      file: apps/order-service/compose.yml
      lifecycle-management: NONE
      start:
        command: up
      stop:
        command: stop




