spring:
  application:
    name: mini-ecomm
  sql:
    init:
      mode: always
      schema-locations: classpath:create_tables.sql
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: kj
    password: kj
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      file: apps/order-service/compose.yml
      lifecycle-management: NONE
      start:
        command: up
      stop:
        command: stop




